# Generated by Django 3.2.6 on 2021-08-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('distance', models.IntegerField(verbose_name='расстояние, км')),
                ('route', models.CharField(max_length=200, verbose_name='маршрут')),
                ('weight', models.FloatField(verbose_name='вес в тоннах')),
                ('free', models.BooleanField(default=True, verbose_name='свободен или в рейсе')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='марка')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('registration_mark', models.CharField(max_length=50, verbose_name='регистрационный знак')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=50, verbose_name='цвет')),
                ('carrying', models.FloatField(verbose_name='грузоподъемность в тоннах')),
                ('free', models.BooleanField(default=True, verbose_name='свободен или в рейсе')),
                ('fuel_consumption', models.FloatField(verbose_name='расход топлива')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='my_logistic.cars', verbose_name='водитель')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='дата принятия заявки')),
                ('execution', models.CharField(max_length=50, verbose_name='статус')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='my_logistic.cars', verbose_name='машина')),
                ('cargos', models.ManyToManyField(to='my_logistic.Cargo', verbose_name='груз')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
