# Generated by Django 3.2.6 on 2021-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(verbose_name='вес в кг'),
        ),
    ]
