# Generated by Django 3.2.6 on 2021-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_logistic', '0002_alter_cargo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='carrying',
            field=models.IntegerField(verbose_name='грузоподъемность в кг'),
        ),
    ]
