# Generated by Django 3.2.6 on 2021-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_logistic', '0003_alter_cars_carrying'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='заявка доставлена либо нет'),
        ),
    ]
