# Generated by Django 3.2.6 on 2021-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_logistic', '0004_applications_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='груз доставлен'),
        ),
    ]
